[project]
name = "reconciliation-api"
version = "0.1.0"
description = "For messy Irish geographic data."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "uvicorn[standard]",
    "pytest>=9.0.3",
    "pandas>=3.0.5",
]

[dependency-groups]
dev = [
    "httpx2>=2.12.0",
    "icecream>=2.2.0",
    "pandas-stubs>=3.0.5.260730",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-s -v"
