[project]
name = "reconciliation-api"
version = "0.1.0"
description = "For messy Irish geographic data."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "uvicorn[standard]",
    "pytest>=9.0.3",
]

[dependency-groups]
dev = ["icecream>=2.2.0"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
